import {
  contactInfo,
  ctaContent,
  faqContent,
  floorPlansContent,
  focusCardsContent,
  homeAmenityPanels,
  homeHeroRailMedia,
  heroContent,
  neighborhoodContent,
  siteMetadata,
  statsContent,
  testimonialsContent,
} from "@/config/content";
import { galleryItems } from "@/data/siteContent";
import type { EditableSiteDocument } from "@/types/editable-content";

export const EDITABLE_CONTENT_VERSION = 1;

export const defaultTheme: EditableSiteDocument["theme"] = {
  colors: {
    primary: "198 65% 40%",
    accent: "172 44% 36%",
    background: "210 30% 97%",
    foreground: "218 24% 18%",
    secondary: "206 24% 92%",
    muted: "208 16% 89%",
    border: "208 18% 82%",
  },
  fonts: {
    body: "Plus Jakarta Sans, sans-serif",
    display: "Plus Jakarta Sans, sans-serif",
  },
  fontSize: {
    heroTitle: "clamp(2.5rem, 5vw, 4.5rem)",
    sectionTitle: "clamp(1.75rem, 3vw, 2.75rem)",
    body: "1rem",
  },
  spacing: {
    sectionPadding: "clamp(3rem, 6vw, 6rem)",
    contentMaxWidth: "1140px",
  },
  radius: "0.75rem",
};

export const defaultEditableSiteDocument: EditableSiteDocument = {
  version: EDITABLE_CONTENT_VERSION,
  updatedAt: new Date().toISOString(),
  theme: defaultTheme,
  global: {
    siteName: "The Flats @ 1204",
    cityLabel: "Atlanta",
    tagline: siteMetadata.tagline,
    description: siteMetadata.description,
    phone: contactInfo.phone,
    email: contactInfo.email,
    addressLine: contactInfo.address.full,
    hoursLine: "Mon–Fri 9am–6pm, Sat 10am–4pm",
    navCtaText: "Book a Tour",
    navCtaLink: "/contact",
    navLinks: [
      { to: "/", label: "Home" },
      { to: "/gallery", label: "Gallery" },
      { to: "/contact", label: "Contact" },
    ],
    footerBadges: ["1BR / 2BR / 3BR", "Pet Friendly"],
    seoTitleSuffix: "Apartments Atlanta",
  },
  home: {
    sectionVisibility: {
      stats: true,
      residences: true,
      unitExplorer: true,
      amenities: true,
      why: true,
      neighborhood: true,
      testimonials: true,
      faq: true,
      map: true,
      finalCta: true,
      mobileBar: true,
    },
    hero: {
      tagline: heroContent.tagline,
      title: heroContent.title,
      highlightText: "Modern. Warm. Effortless.",
      description: heroContent.description,
      primaryCta: {
        text: heroContent.cta.primary.text,
        link: heroContent.cta.primary.link,
      },
      secondaryCta: {
        text: heroContent.cta.secondary.text,
        link: heroContent.cta.secondary.link,
      },
      heroRailMedia: homeHeroRailMedia,
    },
    stats: statsContent,
    focusCards: focusCardsContent,
    floorPlans: floorPlansContent.map((plan) => ({
      ...plan,
      priceRange: plan.priceRange ?? "Contact for pricing",
    })),
    amenityPanels: homeAmenityPanels,
    whyCards: [
      {
        title: "Practical Floor Plans",
        description: "Layouts are planned around real furniture placement and daily movement, so your living room and kitchen feel useful from day one.",
        tag: "Space Planning",
        icon: "building",
      },
      {
        title: "Pet-Ready Living",
        description: "Dedicated pet-friendly features and nearby walking routes make routines easier for residents balancing work, family, and pets.",
        tag: "Pet Friendly",
        icon: "paw",
      },
      {
        title: "Stress-Free Parking",
        description: "Resident parking is structured for convenience, with clear access patterns that reduce evening congestion and guest confusion.",
        tag: "Everyday Access",
        icon: "car",
      },
      {
        title: "Connected Location",
        description: "Commuter routes, grocery options, and neighborhood services are close enough to save time without sacrificing local character.",
        tag: "Commute Ready",
        icon: "map",
      },
      {
        title: "Reliable Support",
        description: "Leasing and maintenance support are designed around response clarity, so residents know what to expect and when.",
        tag: "Support Quality",
        icon: "shield",
      },
      {
        title: "Updated Interiors",
        description: "Updated finishes and brighter interiors create a clean backdrop that works for different styles without feeling generic.",
        tag: "Interior Refresh",
        icon: "sparkles",
      },
    ],
    neighborhood: {
      eyebrow: "Neighborhood",
      title: neighborhoodContent.title,
      description: neighborhoodContent.description,
      highlights: neighborhoodContent.highlights.map((item) => ({
        title: item.title,
        description: item.description,
        distance: item.distance ?? "Nearby",
      })),
    },
    testimonials: testimonialsContent.map((item) => ({
      quote: item.quote,
      name: item.name,
      designation: item.designation,
    })),
    faq: faqContent.map((item) => ({
      question: item.question,
      answer: item.answer,
      category: item.category ?? "General",
    })),
    finalCta: {
      tagline: ctaContent.tagline,
      title: ctaContent.title,
      description: ctaContent.description,
      primary: {
        text: ctaContent.actions.primary.text,
        link: ctaContent.actions.primary.link,
      },
      secondary: {
        text: ctaContent.actions.secondary.text,
        link: ctaContent.actions.secondary.link,
      },
    },
    ui: {
      residencesEyebrow: "Residences",
      residencesTitle: "Choose Your Layout",
      residencesDescription: "Practical kitchen flow, usable living space, and room options that scale from solo renters to larger households.",
      unitExplorerEyebrow: "Unit Explorer",
      unitExplorerTitle: "Interactive Layout Preview",
      unitExplorerDescription: "Placeholder copy: imagine each card expanding into full availability details, sample furniture staging notes, and move-in timing guidance. This section is intentionally text-rich so you can validate rhythm, spacing, and readability before final leasing copy is approved.",
      amenitiesEyebrow: "Amenities",
      amenitiesTitle: "Media-Rich Amenity Experience",
      amenitiesDescription: "Scroll through each amenity to see how daily life, comfort, and location work together at Baba Flats.",
      whyEyebrow: "Why Baba Flats",
      whyTitle: "Designed for Daily Life, Not Marketing Hype",
      whyDescription: "Baba Flats focuses on practical value: efficient layouts, responsive support, connected location access, and day-to-day comfort that holds up over time. Each feature below highlights how the property supports real routines, not just brochure claims.",
      whyStickyEyebrow: "Resident Experience",
      whyStickyTitle: "Practical features that blend into everyday living.",
      whyStickyDescription: "From commute flow and pet routines to support responsiveness and layout efficiency, each decision is designed to reduce friction and improve day-to-day comfort.",
      neighborhoodStickyEyebrow: "Atlanta Access",
      neighborhoodStickyTitle: "Live close to what matters most.",
      neighborhoodStickyDescription: "Daily essentials, commute routes, and weekend options are all nearby. The neighborhood offers practical convenience while keeping a residential feel.",
      testimonialsEyebrow: "Resident Stories",
      testimonialsTitle: "What Residents Are Saying",
      testimonialsDescription: "Clear, high-contrast cards improve readability while preserving a premium animated feel.",
      faqEyebrow: "FAQ",
      faqTitle: "Leasing Questions at a Glance",
      faqDescription: "Placeholder copy: this FAQ is intentionally expanded so you can preview real-world content volume, scan behavior, and accordion spacing across breakpoints.",
      faqHelpEyebrow: "Need More Help?",
      faqHelpTitle: "Questions before booking a tour?",
      faqHelpDescription: "We answered the most common leasing, move-in, and resident support questions below. If you need specifics for your timeline, our team can help directly.",
      faqHelpPrimaryLabel: "Call Leasing",
      faqHelpSecondaryLabel: "Contact Page",
      mapEyebrow: "Map & Address",
      mapTitle: "Find Baba Flats",
      mapDescription: "Placeholder location context: this section can include parking instructions, landmark tips, and best entry points for scheduled tours.",
      mapCardOfficeLabel: "Leasing Office",
      mapCardCallLabel: "Call",
      mapCardHoursLabel: "Hours",
      mobilePrimaryLabel: "Call Now",
      mobileSecondaryLabel: "Book Tour",
    },
  },
  gallery: {
    sectionVisibility: {
      hero: true,
      media: true,
      cta: true,
    },
    heroEyebrow: "Dedicated Media Page",
    heroTitle: "The Flats @ 1204 Gallery",
    heroDescription: "Explore exterior scenes, interior details, amenities, and floor plans.",
    heroImage: "/images/aerial.jpg",
    categories: [
      { name: "Exterior", subcategories: ["Building", "Grounds"] },
      { name: "Interiors", subcategories: ["Living", "Kitchen", "Bedroom"] },
      { name: "Amenities", subcategories: ["Dog Park", "Laundry"] },
      { name: "Floor Plans", subcategories: [] },
    ],
    items: galleryItems.map((item) => ({ ...item, type: "image" as const })),
    cta: {
      eyebrow: "Next Step",
      title: "Schedule a Tour After Browsing",
      description: "Ready to visit in person? Contact leasing for availability, pricing, and current move-in options.",
      primary: {
        text: `Call ${contactInfo.phone}`,
        link: `tel:${contactInfo.phone.replace(/\D/g, "")}`,
      },
      secondary: {
        text: "Book Tour",
        link: "/contact",
      },
    },
  },
  contact: {
    sectionVisibility: {
      hero: true,
      form: true,
      map: true,
    },
    heroEyebrow: "Contact & Leasing",
    heroTitle: "Book a Tour at Baba Flats",
    heroDescription: "Share your preferred layout, timeline, and tour format. Our leasing team will confirm current options and next steps.",
    heroImage: "/images/exterior.jpg",
    mapEmbedUrl: contactInfo.mapEmbedUrl,
    officeHoursTitle: "Leasing Desk",
    officeHours: ["Mon–Fri: 9 AM – 6 PM", "Saturday: 10 AM – 4 PM", "Sunday: By appointment"],
    tourFormTitle: "Tell Us What You Need",
    tourFormDescription: "Quick qualification inputs, concise details, and a clear action path.",
    formOptions: {
      bedroom: ["1BR", "2BR", "3BR"],
      moveIn: ["Immediately", "Within 30 days", "Within 60 days"],
      tourType: ["In-person", "Virtual first"],
    },
    submitText: "Submit Tour Request",
    integrations: {
      smtp: {
        enabled: false,
        endpoint: "",
        method: "POST",
        authHeader: "",
        fromEmail: "",
        toEmail: "",
        subjectTemplate: "New Tour Request - {{fullName}}",
      },
      submitHooks: [
        {
          name: "Lead webhook",
          url: "",
          method: "POST",
          enabled: false,
          sendFormData: true,
          headersJson: "{}",
        },
      ],
    },
    ui: {
      callButtonPrefix: "Call",
      browseButtonText: "Browse Gallery",
      formEyebrow: "Tour Request Form",
      infoBullets: ["Preferred floor plan type", "Move-in timeline", "Tour preference and notes"],
      featureBadges: ["Pet Friendly", "On-site Laundry", "Responsive Leasing"],
      labels: {
        fullName: "Full Name",
        email: "Email",
        phone: "Phone",
        bedroomType: "Bedroom Type",
        moveIn: "Move-In",
        tourPreference: "Tour Preference",
        message: "Message",
      },
      placeholders: {
        fullName: "Your name",
        email: "you@email.com",
        phone: "(555) 123-4567",
        message: "Anything you'd like the leasing team to know",
      },
    },
  },
};
